language: python
python: "3.12"
sudo: false
cache: pip
env:
  - TOXENV=no-flask-caching
  - TOXENV=lint
  - TOXENV=docs

addons:
  apt:
    packages:
      - libcairo2-dev

install:
  - pip install tox

script: "./.travis.sh"

matrix:
  include:
    - python: "3.12"
      env:
      - TOXENV=py312
    - python: "3.11"
      env:
      - TOXENV=py311
    - python: "3.10"
      env:
      - TOXENV=py310
    - python: "3.9"
      env:
      - TOXENV=py39
    - python: "3.8"
      env:
      - TOXENV=py38
    - python: "3.13"
      env:
      - TOXENV=py313
    - python: "3.14-dev"
      env:
      - TOXENV=py314
  allow_failures:
    - python: "3.14-dev"
